config/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static


from dashboard import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('accounts/', include('registration.backends.default.urls')),
    path('questions/', include('questions.urls', namespace='questions')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('matches/', include('matches.urls', namespace='matches')),
    path('likes/', include('likes.urls', namespace='likes')),
]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likes/urls.py
from django.urls import path
from . import views 

app_name = 'likes'
urlpatterns = [
    path('user/<int:id>/', views.user_like, name='like_user'),
]

questions/urls.py
from django.urls import path
from . import views 

app_name = 'questions'
urlpatterns = [
    path('', views.home, name='home'),
    path('<int:id>/', views.single, name='single'),
]

questions/models.py
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save, pre_save
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from django.urls import reverse
from django.dispatch import receiver


class QuestionManager(models.Manager):
    def get_unanswered(self, user):
        # wit Q look up is allows as to grab the model that is associated to other models 
        q1 = Q(useranswer__user=user)
        qs = self.exclude(q1)
        return qs 


class Question(models.Model):
    text = models.TextField(_("Text"))
    active = models.BooleanField(_("Active"), default=True)
    draft  = models.BooleanField(_("Draft"), default=False)
    timestamp = models.DateTimeField(_("Timestamp"), auto_now=False, auto_now_add=True)

    objects = QuestionManager()
    
    class Meta:
        verbose_name = _("Question")
        verbose_name_plural = _("Questions")

    def __str__(self):
        return self.text[:10]


class Answer(models.Model):
    """Model definition for Answer."""

    question = models.ForeignKey(Question, verbose_name=_("Question"), on_delete=models.CASCADE)
    text = models.CharField(_("Text"), max_length=250)
    active = models.BooleanField(_("Active"), default=True)
    draft  = models.BooleanField(_("Draft"), default=False)
    timestamp = models.DateTimeField(_("Timestamp"), auto_now=False, auto_now_add=True)

    class Meta:
        """Meta definition for Answer."""

        verbose_name = 'Answer'
        verbose_name_plural = 'Answers'

    def __str__(self):
        """Unicode representation of Answer."""
        return self.text[:10]


LEVELS = (
    ('Mandatory', 'Mandatory'),
    ('Very Important', 'Very Important'),
    ('Somewhat Important', 'Somewhat Important'),
    ('Not important', 'Not important'),
)


class UserAnswer(models.Model):
    user = models.ForeignKey(User, verbose_name=_("User"), on_delete=models.CASCADE)
    question = models.ForeignKey(Question, verbose_name=_("Question"), on_delete=models.CASCADE)
    my_answer = models.ForeignKey(Answer, verbose_name=_("Answer"), on_delete=models.CASCADE, related_name="user_answer")
    my_answer_importance = models.CharField(_("My Answer Importance"), max_length=50, choices=LEVELS)
    # to undrestand the weight of every answer we have to measure them with points
    # i put the default value to "-1" it means that our score never hits "-1" and also never gonna be "-1" after we save too
    # because i put it "300, 200, ..." if i put "0" so it clash with my code because i have already defined "0" 
    my_points = models.IntegerField(_("My points"), default=-1) 
    their_answer = models.ForeignKey(Answer, verbose_name=_("Their answer"), 
                                    on_delete=models.CASCADE, 
                                    related_name="match_answer",
                                    null=True, blank=True
                                    )
    their_answer_importance = models.CharField(_("Their answer importants"), max_length=50, choices=LEVELS)
    timestamp = models.DateField(_("Timestamp"), auto_now=False, auto_now_add=True)
    their_points = models.IntegerField(_("My points"), default=-1) 


    class Meta:
        verbose_name = _("useranswer")
        verbose_name_plural = _("useranswers")

    def __str__(self):
        return self.my_answer.text[0:10]

    def get_absolute_url(self):
        return reverse("useranswer_detail", kwargs={"pk": self.pk})


def score_importance(importants_level):
    if importants_level == "Mandatory":
        points = 300 
    elif importants_level == "Very Important":
        points = 200
    elif importants_level == "Somewhat Important":
        points = 50
    elif importants_level == "Not important":
        points = 0
    else:
        points = 0
    return points

@receiver(pre_save, sender=UserAnswer)
def update_user_answer_score(sender, instance, *args, **kwargs):
    my_points = score_importance(instance.my_answer_importance)
    instance.my_points = my_points
    their_points = score_importance(instance.their_answer_importance)
    instance.their_points = their_points
# instead of @receiver you can use the line bellow as well
# pre_save.connect(update_user_answer_score, sender=UserAnswer)

# sender is the model and instance is the instance of model and created is a boolean value
# def update_user_answer_score(sender, instance, created, *args, **kwargs):
# 	# my_points = score_importance(instance.my_answer_importance)
# 	# instance.my_points = my_points
# 	# their_points = score_importance(instance.their_importance)
# 	# instance.their_points = their_points
# 	# instance.save() ## don't save like this
# 	if created:
# 		if instance.my_points == -1:
# 			my_points = score_importance(instance.my_answer_importance)
# 			instance.my_points = my_points
# 			instance.save()

# 		if instance.their_points == -1:
# 			their_points = score_importance(instance.their_answer_importance)
# 			instance.their_points = their_points
# 			instance.save()

# post_save.connect(update_user_answer_score, sender=UserAnswer)

questions/forms.py
from django import forms 
from .models import LEVELS, Question, Answer

class UserResponseForm(forms.Form):
    question_id = forms.IntegerField()
    answer_id = forms.IntegerField()
    importants_level = forms.ChoiceField(choices=LEVELS)
    their_answer_id = forms.IntegerField()
    their_importants_level = forms.ChoiceField(choices=LEVELS)

    def clean_question_id(self):
        question_id = self.cleaned_data['question_id']
        try:
            obj = Question.objects.get(id=question_id)
        except:
            raise forms.ValidationError("There was an error with this question please try again.")
        return question_id

    def clean_answer_id(self):
        answer_id = self.cleaned_data['answer_id']
        try:
            obj = Answer.objects.get(id=answer_id)
        except:
            raise forms.ValidationError("There was an error with Answer pleas try again")
        return answer_id

    def clean_their_answer_id(self):
        their_answer_id = self.cleaned_data['their_answer_id']
        try:
            obj = Answer.objects.get(id=their_answer_id)
        except:
            if their_answer_id == -1:
                return their_answer_id
            else: 
                raise forms.ValidationError("There was an error with the answer you provide for them.")
        return their_answer_id

questions/views.py
from django.shortcuts import Http404, get_object_or_404, redirect, render, reverse
from django.contrib import messages

from matches.signals import user_matches_update
from .models import Question, Answer, UserAnswer 
from .forms import UserResponseForm


def single(request, id):
    if request.user.is_authenticated:
        queryset = Question.objects.all().order_by('-timestamp')
        instance = get_object_or_404(Question, id=id)

        # we are working with pre existing UserAnswer or creating a new one 
        # and that's what try block is going to do for us
        try:
            user_answer = UserAnswer.objects.get(user=request.user, question=instance)
            updated_q = True
        except UserAnswer.DoesNotExist:
            user_answer = UserAnswer()
            updated_q = False
        except UserAnswer.MultipleObjectsReturned:
            user_answer = UserAnswer.objects.filter(user=request.user, question=instance)[0]
            updated_q = True
        except:
            user_answer = UserAnswer()
            updated_q = False

        form = UserResponseForm(request.POST or None)
        if form.is_valid():
            print(form.cleaned_data)
            print("This is the request: ",request.POST)
            # question_id = form.cleaned_data.get('question_id')
            # answer_id = form.cleaned_data.get('answer_id')
            # question_instance = Question.objects.get(id=question_id)
            # answer_instance = Answer.objects.get(id=answer_id)
            # or you can do as follows as well

            question_id = form.cleaned_data['question_id']
            answer_id = form.cleaned_data['answer_id'] 
            importants_level = form.cleaned_data['importants_level']
            their_answer_id = form.cleaned_data['their_answer_id']
            their_importants_level = form.cleaned_data['their_importants_level']

            question_instance = Question.objects.get(id=question_id)
            answer_instance = Answer.objects.get(id=answer_id)
            
            user_answer = UserAnswer()
            user_answer.user = request.user
            user_answer.question = question_instance
            user_answer.my_answer = Answer.objects.get(id=answer_id)
            user_answer.my_answer_importance = importants_level
            if their_answer_id != -1:
                their_answer_instance = Answer.objects.get(id=their_answer_id)
                user_answer.their_answer = their_answer_instance
                user_answer.their_answer_importance = their_importants_level
            else:
                user_answer.their_answer = None
                user_answer.their_answer_importance = "not important"
            user_answer.save()
            
            # send the signal after saving the response
            user_matches_update.send(user=request.user, sender=user_answer.__class__)
            
            if updated_q:
                messages.success(request, "your response has been updated successfully  her is the link <a href='wwww.google.com'>info</a>.", extra_tags="safe updated")
            else:
                messages.success(request, "your response has been saved successfully.")

            next_q = Question.objects.get_unanswered(request.user).order_by('?')
            if next_q.count()>0:
                next_q_instance = next_q.first()
                return redirect(reverse("questions:single", kwargs = {'id':next_q_instance.id})) 
            else:
                return redirect(reverse("home"))

        context = {
            'form': form,
            'instance': instance,
            'user_answer': user_answer
        }
        return render(request, "questions/single.html", context)
    else:
        raise Http404


def home(request):
    if request.user.is_authenticated:
        form = UserResponseForm(request.POST or None)
        if form.is_valid():
            print(form.cleaned_data)
            # question_id = form.cleaned_data.get('question_id')
            # answer_id = form.cleaned_data.get('answer_id')
            # question_instance = Question.objects.get(id=question_id)
            # answer_instance = Answer.objects.get(id=answer_id)
            question_id = form.cleaned_data['question_id']
            answer_id = form.cleaned_data['answer_id']
            question_instance = Question.objects.get(id=question_id)
            answer_instance = Answer.objects.get(id=answer_id)
            print(question_instance.text)
            print(answer_instance.text)
        queryset = Question.objects.all().order_by('-timestamp')
        instance = queryset[1]
        context = {
            'form': form,
            'instance': instance
        }
        return render(request, "questions/home.html", context)
    else:
        raise Http404

templates/questions/home.html
{% extends 'base.html' %}
{% load static %}

{% block style %}

{% endblock style %}

{% block content %}
<div class="row">
    <div class="col-sm-8">
        <h1>Dashboard</h1>
        
        {% if mutual_likes %}
            <div class="col-sm-12">
                <h3>Mutual interest</h3>
                {% for liked_user in mutual_likes %}
                    <div class="col-sm-3 text-center">
                        <a href="{{liked_user.profile.get_absolute_url}}">
                            {{liked_user}}
                            <br>
                            {% if liked_user.profile.picture %}
                                <img src="{{liked_user.profile.picture.url}}" alt="user profile picture" class="img-responsive center-block img-featured-match">
                            {% else %}
                                <img src="{% static 'img/avatar.jpeg' %}" alt="user profile image" class="img-responsive center-block img-featured-match">
                            {% endif %}
                        </a>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
            
    </div>
    <div class="col-sm-4">
        <div class="col-sm-12">
            <h3>Matches</h3>
            <hr/>
        </div>
        
        {% for match_user, percent in matches %}
            <div class="col-sm-4 text-center">
                <a href="{{match_user.profile.get_absolute_url}}">
                    {{match_user}}
                    <br>
                    {% if match_user.profile.picture %}
                        <img src="{{match_user.profile.picture.url}}" alt="user profile picture" class="img-responsive center-block img-featured-match">
                    {% else %}
                        <img src="{% static 'img/avatar.jpeg' %}" alt="user profile image" class="img-responsive center-block img-featured-match">
                    {% endif %}
                    {{percent}}
                </a>
            </div>
        {% endfor %}


        <div class="col-sm-12">
            <h1>Suggested positions</h1>
            <hr/>
        </div>
        
        {% for pos in positions %}
            <div class="col-sm-4">
                <p class="lead"><a href="{{pos.get_match_url}}">{{pos.job.title}}</a></p>
            </div>
        {% endfor %}


        <div class="col-sm-12">
            <h1>Suggested locations</h1>
            <hr/>
        </div>
        
        {% for loc in locations %}
            <div class="col-sm-4">
                <p class="lead"><a href="{{loc.get_match_url}}">{{loc.location.name}}</a></p>
            </div>
        {% endfor %}


        <div class="col-sm-12">
            <h1>Suggested employers</h1>
            <hr/>
        </div>
        
        {% for emp in employers %}
            <div class="col-sm-4">
                <p class="lead"><a href="{{emp.get_match_url}}">{{emp.employer.name}}</a></p>
            </div>
        {% endfor %}
                    
    </div>
</div>
{% endblock content %}
    

templates/questions/single.html
{% extends 'base.html' %}

{% block content %}
    <!-- i'm adding title size here to just manipulate the size of title in dashboard  -->
    {% include 'questions/user_response_form.html' with instance=instance form=form %}
        
{% endblock content %}
    

templates/questions/user_response_form.html
<div class=" {% if center_text %} text-center {% endif %}">
    <form action="{% url 'questions:single' id=instance.id %}" method="POST">
        {{form.errors}}
        {% csrf_token %}
        
        {% if title_size %}
            <h{{title_size}}>{{instance.text}}?</h{{title_size}}>
        {% else %}
            <h1>{{instance.text}}?</h1>
        {% endif %}
            
        <input type="hidden" name="question_id" value="{{instance.id}}">
        
        {% if title_size %}
            <h{{title_size|add:1}}>Your answer </h{{title_size|add:1}}>
        {% else %}
            <h2>Your answer </h2>
        {% endif %}
        {% for ans in instance.answer_set.all %}
            <input type="radio" name="answer_id" 
                value="{{ans.id}}" 
                {% if user_answer.my_answer.id == ans.id %} checked=checked {% endif %} /> &nbsp;{{ans.text}} <br>
        {% endfor %}
        <br>
        Importance: &nbsp; {{form.importants_level}}

        {% if title_size %}
            <h{{title_size|add:1}}>Their answer </h{{title_size|add:1}}>
        {% else %}
            <h2>Their answer </h2>
        {% endif %}
        {% for ans in instance.answer_set.all %}
            <input type="radio" name="their_answer_id" 
            value="{{ans.id}}"
            {% if user_answer.their_answer.id == ans.id %} checked=checked {% endif %} /> &nbsp;{{ans.text}} <br>
        {% endfor %}
        <input type="radio" name="their_answer_id" value="-1" 
            {% if not user_answer.their_answer.id %} checked=checked {% endif %} /> &nbsp; Holds no importance<br>
        <br>
        Importance:&nbsp; {{form.their_importants_level}}
        <br><br>
        <input class="btn btn-success" type="submit" value="Save and continue">
    </form>
</div>