config/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static


from dashboard import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('accounts/', include('registration.backends.default.urls')),
    path('questions/', include('questions.urls', namespace='questions')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('matches/', include('matches.urls', namespace='matches')),
    path('likes/', include('likes.urls', namespace='likes')),
]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likes/urls.py
from django.urls import path
from . import views 

app_name = 'likes'
urlpatterns = [
    path('user/<int:id>/', views.user_like, name='like_user'),
]

profiles/urls.py
from django.urls import path
from . import views 

app_name = 'profiles'
urlpatterns = [
    path('me/', views.my_profile, name="my_profile"),
    path('edit/', views.edit_profile, name="edit_profile"),
    path('<str:username>/', views.profile, name='profile'),
    path('jobs/add/', views.add_job, name="add_jobs"),
    path('jobs/update/', views.update_jobs, name="update_jobs"),
]

templates/about.html
{% extends "base.html" %}



{% block content %}

<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>
<h1>About Us</h1>
<p>This is about us. This is about us.This is about us.This is about us.This is about us.This is about us.This is about us.This is about us.</p>
<p>This is about us. This is about us.This is about us.This is about us.This is about us.This is about us.This is about us.This is about us.</p>
<p>This is about us. This is about us.This is about us.This is about us.This is about us.This is about us.This is about us.This is about us.</p>
</div>

</div>


{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block head_title %}Danishyar Match finder{% endblock %}</title>

    {% include 'head_css.html' %}

      <style>
        .alert-top-message {
              margin-top: -19px;
        }
      {% block style %}{% endblock %}
      </style>



  </head>

  <body>
  {% include 'navbar.html' %}
  {% if messages %} 
    <div class="alert alert-success alert-top-message" role="alert">
      <div class="container text-center">
          {% for message in messages %}
          {% if "safe" in message.tags %} {{message|safe}} {% else %} {{ message }} {% endif %} <br>
          {% endfor %}
      </div>
    </div>
  {% endif %}
    {% block jumbotron %}
          
            {% endblock %}
    <div class="container">
            

          
            {% block content %}

            {% endblock %}
              

    </div> <!-- /container -->

    {% include "javascript.html" %}
    
    
  </body>
</html>

templates/example_fluid.html
{% extends "base.html" %}

{% block jumbotron %}
_
{% endblock %}

{% block content %}

<div class="row">
<div class="col-sm-3" style='background-color:orange;'>




             .col-md-4



             </div>

</div>

<div class="row">
  <div class="col-md-8 col-sm-6" style='background-color:red;'>.col-md-8
        <div class="row">
             <div class="col-md-6 col-sm-8 col-xs-2" style='background-color:orange;'>




             .col-md-4



             </div>
            <div class="col-md-6 col-sm-4 col-xs-10" style='background-color:yellow;'>.col-md-4</div>

        </div>

  </div>
  <div class="col-md-4 col-sm-6" style='background-color:blue;'>.col-md-4

    <div class="row">
             <div class="col-md-12" style='background-color:purple;'>.col-md-4</div>

        </div>

    </div>
</div>
<!-- <div class="row">
  <div class="col-md-4">.col-md-4</div>
  <div class="col-md-4">.col-md-4</div>
  <div class="col-md-4">.col-md-4</div>
</div>
<div class="row">
  <div class="col-md-6">.col-md-6</div>
  <div class="col-md-6">.col-md-6</div>
</div> -->

{% endblock %}

templates/forms.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}





<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>


{% if title %}
<h1 class='{% if title_align_center %}text-align-center{% endif %}'>{{ title }}</h1>
{% endif %}

<form method='POST' action='' enctype="multipart/form-data">{% csrf_token %}
{{ form|crispy }}

<input class='btn btn-default' type='submit' value='Submit' />

</form>
</div>
</div>
{% endblock %}

templates/formset.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}





<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>


{% if title %}
<h1 class='{% if title_align_center %}text-align-center{% endif %}'>{{ title }}</h1>
{% endif %}

<form method='POST' action=''>{% csrf_token %}
<!-- {{ form|crispy }} -->
    {{ formset.management_form }}
        {% for form in formset %}
        {{ form|crispy }}
        <br>
        <hr>
        <br>
        {% endfor %}

<input class='btn btn-default' type='submit' value='Submit' />

</form>
</div>
</div>
{% endblock %}

templates/head_css.html
{% load static %}
    <!-- Bootstrap core CSS -->
    <!-- <link href="../../dist/css/bootstrap.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- <img src="{% static "my_app/myexample.jpg" %}" alt="My image"/> -->
    <!-- Custom styles for this template -->
    <!-- <link href="navbar-static-top.css" rel="stylesheet"> -->
    <link href="{% static 'css/navbar-static-top.css' %}" rel="stylesheet">
     <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    -->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

templates/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block head_title %}Welcome | {{ block.super }}{% endblock %}

<style>
{% block style %}
.navbar-static-top {
	margin-bottom: 0px !important;
}

.jumbotron {
	background-color:#0E3D14;
	color: #FFF;
}

{% endblock %}
</style>


     
{% block jumbotron %}
 {% if not request.user.is_authenticated %}

<div class="jumbotron">
 <div class="container">
	<div class="row">
		<div class='col-sm-6'>
		<h1>Let's Make some noise</h1>
		<p>The MVP Landing project is designed to get your project started. The goal is to help you launch as soon as possible with the least amount of investment using time or money. Join Us today.</p>
		<p>
		<a class="btn btn-lg btn-primary" href="" role="button">Join Us &raquo;</a>
		</p>
		</div>
		<div class='col-sm-6' >
			<iframe width="560" height="315" src="https://www.youtube.com/embed/MBdVXkSdhwU" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
 		</div>
		</div>
	</div>
 </div>
 {% endif %}
{% endblock %}




{% block content %}
 {% if request.user.is_authenticated %}
<h1>You are logged in!</h1>

	{% if queryset %}
	<h2>Welcome Staff</h2>
	<table class='table'>
	{% for instance in queryset %}
		<tr><td>{{ forloop.counter }}</td><td>{{ instance.email }}</td><td>{{ instance.full_name }}</td><td>{{ instance.timestamp|timesince }} ago</td></tr>
		{% if instance.email == "abc@gmail.edu" %}
		<tr><td>is equal</td></tr>
		{% endif %}
	{% endfor %}
	</table>

	{% endif %}

 {% else %}
<div class="row">

  <div class="col-sm-3 pull-right">
  	
			<p class='lead text-align-center'>{{ title }}</p>

			<form method='POST' action=''>{% csrf_token %}
			{{ form|crispy }}

			<input class='btn btn-primary' type='submit' value='Sign Up' />

			</form>
	</div>

	<div class='col-sm-3'>
<p class='lead text-align-center'>Django &amp; Bootstrap</p>
			<img src='{% static "img/marketing1.jpg" %}' class='img-responsive' />
</div>

<div class='col-sm-3'>
<p class='lead text-align-center'>Created for Starters 
<br/>
<span class='fa-stack fa-lg fa-5x'>
<i class='fa fa-comment-o fa-stack-2x'></i>
<i style='color:yellow;' class="fa fa-bolt fa-stack-1x"></i>

</span>
</p>

</div>

<div class='col-sm-3'>
<p class='lead text-align-center'>Always Open Source <br/><br/>

<span class="fa-stack fa-lg fa-5x">
<i class="fa fa-circle-o-notch fa-stack-2x"></i>
  <!-- <i class="fa fa-square-o fa-stack-2x"></i> -->
  <i class="fa fa-github fa-stack-1x"></i>
</span>
</p>


</div>


</div>
{% endif %}

{% endblock %}

templates/javascript.html
{% load static %}
<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

templates/navbar.html
   {% load static %}

   <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Danishyar Match finder</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'contact' %}">Contact</a></li>
          </ul>


          <ul class="nav navbar-nav navbar-right">
          {% if request.user.is_authenticated %}
            <li><a href="{% url 'profiles:my_profile' %}">my profile</a></li>
            <li><a href="{% url 'auth_logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'registration_register' %}">Register</a></li>
            {% endif %}
          </ul>

          {% if not request.user.is_authenticated and not "/accounts/login" in request.get_full_path %}
            <form class='navbar-form navbar-right' method='POST' action='{% url "auth_login" %}'>{% csrf_token %}
              <div class='form-group'>
                  <input type='text' class='form-control' name='username' placeholder='Username' /> 
              </div>
              <div class='form-group'>
                  <input type='password' class='form-control' name='password' placeholder='Password' />
              </div>
              <button type='submit' class='btn btn-default'>Login</button>
          </form>
          {% endif %}


        </div><!--/.nav-collapse -->
      </div>
    </nav>