config/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static


from dashboard import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('accounts/', include('registration.backends.default.urls')),
    path('questions/', include('questions.urls', namespace='questions')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('matches/', include('matches.urls', namespace='matches')),
    path('likes/', include('likes.urls', namespace='likes')),
]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likes/urls.py
from django.urls import path
from . import views 

app_name = 'likes'
urlpatterns = [
    path('user/<int:id>/', views.user_like, name='like_user'),
]

profiles/urls.py
from django.urls import path
from . import views 

app_name = 'profiles'
urlpatterns = [
    path('me/', views.my_profile, name="my_profile"),
    path('edit/', views.edit_profile, name="edit_profile"),
    path('<str:username>/', views.profile, name='profile'),
    path('jobs/add/', views.add_job, name="add_jobs"),
    path('jobs/update/', views.update_jobs, name="update_jobs"),
]

profiles/models.py
from django.db.models.signals import post_save, pre_save
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from django.urls import reverse

from jobs.models import Job, Location, Employer

def upload_location(instance, filename):
    # extention = filename.split(".")[1]   #if you want to extract the extention as will
    username = str(instance.user.username)
    # return "%s/%s" %(username, filename)
    # return f"{username}/profile.{extention}"
    return f"{username}/{filename}"


class Profile(models.Model):
    """Model definition for Profile."""

    user = models.OneToOneField(User, verbose_name=_("User"), on_delete=models.CASCADE)
    picture = models.ImageField(_("Picture"), upload_to=upload_location,
                                default="avatar.jpeg",
                                height_field=None, 
                                width_field=None, 
                                max_length=None,
                                blank=True, null=True
                                )
    location = models.CharField(_("Location"), max_length=100, null=True, blank=True)

    class Meta:
        """Meta definition for Profile."""

        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    def __str__(self):
        """Unicode representation of Profile."""
        return self.user.username
    
    def get_absolute_url(self):
        return reverse("profiles:profile", kwargs={"username": self.user.username})

    def like_link(self):
        return reverse("likes:like_user", kwargs={"id": self.user.id})
    

# why i don't use foreign key? because jobs.models are just for our own  taging of diffrent jobs
# when we add a job also we add those three models and that's the only time we add those staff.
class UserJob(models.Model):

    user = models.ForeignKey(User, verbose_name=_("User"), on_delete=models.CASCADE)
    position = models.CharField(_("Position"), max_length=50)
    location = models.CharField(_("Location"), max_length=50)
    employer_name = models.CharField(_("Employer Name"), max_length=50)

    class Meta:
        verbose_name = _("userjob")
        verbose_name_plural = _("userjobs")

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse("userjob_detail", kwargs={"pk": self.pk})


def post_save_user_job(sender, instance, created, *args, **kwargs):
    job = instance.position.lower() 
    location = instance.location.lower()
    employer_name = instance.employer_name.lower()
    new_job, created = Job.objects.get_or_create(title=job)
    new_location, created = Location.objects.get_or_create(name=location)
    new_employer = Employer.objects.get_or_create(name=employer_name, location=new_location) 

post_save.connect(post_save_user_job, sender=UserJob)

profiles/forms.py
from django import forms 

from .models import UserJob, Profile

class UserJobForm(forms.ModelForm):
    class Meta:
        model = UserJob
        fields = ['position', 'location', 'employer_name']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['picture', 'location']

profiles/views.py
from django.shortcuts import render, get_object_or_404, Http404, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.forms.models import modelformset_factory

from .models import Profile, UserJob
from .forms import UserJobForm, ProfileForm
from matches.models import Match
from likes.models import UserLike

@login_required
def my_profile(request):
    user = get_object_or_404(User, username=request.user)
    profile, created = Profile.objects.get_or_create(user=user)
    jobs = user.userjob_set.all()
    context = {
        "profile": profile,
        "jobs": jobs,
        }
    return render(request, "profiles/my_profile.html", context)

@login_required
def edit_profile(request):
    title = "Edit profile"
    profile, created = Profile.objects.get_or_create(user=request.user)
    form = ProfileForm(request.POST or None, request.FILES or None, instance=profile)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user 
        instance.save()
        return redirect("profiles:my_profile")
    context = {
        "form": form, 
        "title": title
    }
    return render(request, "forms.html", context)


@login_required
def profile(request, username):
    user = get_object_or_404(User, username=username)
    profile, created = Profile.objects.get_or_create(user=user)
    user_like, user_like_created = UserLike.objects.get_or_create(user=request.user)
    do_i_like=False
    if user in user_like.liked_users.all():
        do_i_like = True
    mutual_like = user_like.get_mutual_like(user)
    print(UserLike.objects.get_all_mutual_likes(request.user, 4))
    match, match_created = Match.objects.get_or_create_match(user_a=request.user, user_b=user)
    jobs = user.userjob_set.all()
    context = {
        "profile": profile,
        "match": match,
        "jobs": jobs,
        "mutual_like": mutual_like,
        'do_i_like': do_i_like,
        }
    return render(request, "profiles/profile.html", context)


@login_required
def add_job(request):
    title = "Add job"
    # for example if i wanna edit the jobs so you can do asl follows line of code but i'm commiting here
    # jobs = UserJob.objects.all()[0]
    # form = UserJobForm(request.POST or None, instance=jobs)
    form = UserJobForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user 
        instance.save()
        return redirect("profiles:my_profile")
    context = {
        "form": form, 
        "title": title
    }
    return render(request, "forms.html", context)


@login_required
def update_jobs(request):
    title = "Edit jobs"
    UserJobFormset = modelformset_factory(UserJob, form=UserJobForm)
    queryset = UserJob.objects.filter(user=request.user)
    formset = UserJobFormset(request.POST or None, queryset=queryset)
    if formset.is_valid():
        # here i use instances because it has more than one instance in formset
        instances = formset.save(commit=False)
        for instance in instances:
            instance.user = request.user 
            instance.save()
        return redirect("profiles:my_profile")
        
    context = {
        'title': title,
        'formset': formset
    }
    return render(request, "formset.html", context)

templates/profiles/my_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    profile
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-sm-2">
            <h3>{{profile.user.username}}</h3>
            {% if profile.picture %}
                <img src="{{profile.picture.url}}" width="300px" alt="profile image" lass='img-responsive'>
            {% else %}
                <img src='{% static "img/avatar.jpeg" %}' class='img-responsive' alt="profile image not found" />
            {% endif %}
        </div>
    </div>

{% if jobs %}
    <div class="row">
        <ul>
            
            {% for job in jobs %}
                <li>{{job.position}} in {{job.location}} at {{job.employer_name}}</li>
            {% endfor %}
            <li><a href="{% url 'profiles:update_jobs' %}">edit jobs</a></li>
        </ul>
    </div>
{% else %}
    <p class="lead">you don't have any job please <a href="{% url 'profiles:add_jobs' %}">Add some</a></p>
{% endif %}
    
{% endblock content %}

templates/profiles/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    profile
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-sm-2">
            <h3>{{profile.user.username}}</h3>
            <p class="lead">Match: {{match.get_percent}}</p>
            {% if profile.picture %}
                <img src="{{profile.picture.url}}" alt="profile image">
            {% else %}
                <img src='{% static "img/avatar.jpeg" %}' class='img-responsive' alt="profile image not found" />
            {% endif %}
        </div>
    </div>
    
    <a href="{{profile.like_link}}">{% if do_i_like %} UnLike{% else %} Like{% endif %}</a>
    {% if mutual_like %}
        <p class="lead">You are connected</p>
        <p>Email: {{profile.user.email}}</p>
    {% endif %}
        
{% if jobs %}
    <div class="row">
        <ul>
            
            {% for job in jobs %}
                <li>{{job.position}} in {{job.location}} at {{job.employer_name}}</li>
            {% endfor %}
                
        </ul>
    </div>
{% endif %}
    
{% endblock content %}